.TH FROOT "1" "July 2026" "Froot v1.0.0" "User Commands"
.SH NAME
froot \- execute a command as a different user
.SH SYNOPSIS
.B froot
.RB [ \-huv ]
.RI [ command ]
.SH DESCRIPTION
.B froot
allows a permitted user to execute a command as the superuser or another
.SH OPTIONS
.TP
.B \-h
Display a short help message and exit.
.TP
.B \-u \fIuser\fR
 Run the specified command as this user. The default is root.
.TP
.B \-v
Print the froot version string and exit.
.SH EXIT STATUS
.B froot
returns the exit status of the executed command, or a non-zero exit code if an error occurs.
.SH FILES
.TP
.B /etc/froot.conf
The policy file that defines which users are allowed to run which commands.
.SH BUGS
Report bugs to your issue tracker.
.SH AUTHOR
[Angel Nieto/NopAngel]
.SH SEE ALSO
.BR su (1),
.BR sudo (8)
